name: build
on: push


jobs:
  build:
    runs-on: macos-11
    concurrency: main
    steps:
      - uses: ashutoshvarma/setup-ninja@master
      - uses: actions/checkout@v2
      - name: setup
        run: |
          git clone https://code.qt.io/qt/qt5.git
          cd qt5
          git checkout 6.2.2
      - name: get
        run: |
          cd qt5
          perl init-repository --module-subset=default,-qtwebengine,-qtwayland
      - name: build
        run: |
          mkdir qtout
          export OUTPWD=$PWD/qtout
          mkdir qt6-build
          cd qt6-build
          cmake -GNinja -DCMAKE_INSTALL_PREFIX=$OUTPWD -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -D QT_NO_BUILD_TESTS=ON ../qt5
          cmake --build . --parallel -G "Ninja"
          cmake --install .
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: qtout
          path: qtout
